// This file was generated by lezer-generator. You probably shouldn't edit it.
export const
  Comment = 1,
  Root = 2,
  Block = 5,
  Group = 8,
  Identifier = 9,
  Keyword = 10,
  String = 11,
  Number = 12,
  Char = 13,
  Punctuation = 14,
  Assignment = 15,
  Operator = 16
