// This file was generated by lezer-generator. You probably shouldn't edit it.
export const
  spaces = 83,
  newline = 84,
  LineComment = 1,
  BlockComment = 2,
  Script = 3,
  Data = 4,
  String = 6,
  Immediate = 7,
  Number = 8,
  Section = 10,
  Global = 12,
  Align = 13,
  Register = 15,
  Offset = 28,
  Itype = 52,
  Label = 78
